# Generated by Django 3.1.3 on 2021-02-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('linkDescarga', models.CharField(max_length=300)),
                ('imagen', models.CharField(max_length=50)),
                ('versionApp', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('lenguaje', models.IntegerField(choices=[(1, 'Java'), (2, 'Python'), (3, 'Javascript'), (4, 'Php'), (5, 'C#'), (6, 'C++'), (7, 'Otros')])),
                ('categoria', models.IntegerField(choices=[(1, 'Ofimatica'), (2, 'Video'), (3, 'Audio'), (4, 'Programacion'), (5, 'Música'), (6, 'Mantenimiento Computadores'), (7, 'Otros')])),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoLicencia', models.CharField(max_length=200)),
                ('costoLicencia', models.CharField(max_length=300)),
                ('aplicaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='catalogosApp.aplicacion')),
            ],
        ),
    ]
