# Generated by Django 3.1.3 on 2021-02-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Ofimatica'), (2, 'Video'), (3, 'Audio'), (4, 'Programacion'), (5, 'Música'), (6, 'Mantenimiento Computadores'), (7, 'Otros')], default=1),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='lenguaje',
            field=models.IntegerField(choices=[(1, 'Java'), (2, 'Python'), (3, 'Javascript'), (4, 'Php'), (5, 'C#'), (6, 'C++'), (7, 'Otros')], default=1),
        ),
    ]
