# Generated by Django 3.1.3 on 2021-02-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='aplicaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='catalogosApp.aplicacion'),
        ),
    ]
